# Generated by Django 4.2.16 on 2026-06-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, help_text='Booking ID, e.g. TJ1189178071008', max_length=50, unique=True)),
                ('booking_date', models.DateTimeField(help_text='Date and time the booking was made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1, help_text='Determines the sequence of flight legs in the itinerary')),
                ('airline_name', models.CharField(help_text='e.g. Oman Aviation', max_length=100)),
                ('airline_code', models.CharField(blank=True, help_text='e.g. WY', max_length=10, null=True)),
                ('flight_number', models.CharField(help_text='e.g. 252', max_length=20)),
                ('departure_airport_name', models.CharField(help_text='e.g. Chennai Arpt', max_length=150)),
                ('departure_city', models.CharField(help_text='e.g. Chennai', max_length=100)),
                ('departure_country', models.CharField(help_text='e.g. India', max_length=100)),
                ('departure_terminal', models.CharField(blank=True, help_text='e.g. Terminal 2', max_length=50, null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_airport_name', models.CharField(help_text='e.g. Muscat Internatonal Arpt', max_length=150)),
                ('arrival_city', models.CharField(help_text='e.g. Muscat', max_length=100)),
                ('arrival_country', models.CharField(help_text='e.g. Oman', max_length=100)),
                ('arrival_terminal', models.CharField(blank=True, help_text='e.g. Terminal 1', max_length=50, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.CharField(help_text='e.g. 3h 50m', max_length=30)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('cabin_class', models.CharField(default='Economy', help_text='e.g. Economy, Business', max_length=50)),
                ('fare_type', models.CharField(default='NA', max_length=50)),
                ('checkin_baggage', models.CharField(blank=True, help_text='e.g. 30KG', max_length=50, null=True)),
                ('cabin_baggage', models.CharField(blank=True, help_text='e.g. 7KG', max_length=50, null=True)),
                ('layover_duration', models.CharField(blank=True, help_text='Layover timer after this segment, e.g. 4h 15m', max_length=30, null=True)),
                ('layover_minutes', models.IntegerField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='tickets.booking')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g. MR, MRS, MS', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(help_text='Full passenger name, e.g. MR IMTIYAZ SAIT RAZACK SAIT', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('other_info', models.CharField(blank=True, help_text='Additional identity info, e.g. ( A )', max_length=100, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='tickets.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerSegmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(help_text='Airline PNR for this passenger on this segment, e.g. ONFDOJ', max_length=50)),
                ('ticket_number', models.CharField(blank=True, help_text='Ticket number specific to this segment/passenger', max_length=100, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('meal_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('baggage_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('other_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_details', to='tickets.passenger')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_details', to='tickets.flightsegment')),
            ],
            options={
                'unique_together': {('passenger', 'segment')},
            },
        ),
    ]
