# Generated by Django 4.2.16 on 2026-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsegment',
            name='airline_logo',
            field=models.CharField(blank=True, default='oman-air-logo-circular.png', help_text='Filename of the airline logo, e.g. oman-air-logo-circular.png', max_length=150, null=True),
        ),
    ]
