# Generated by Django 4.2.16 on 2026-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_flightsegment_airline_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsegment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this segment is active and displayed on the printable ticket'),
        ),
    ]
